version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ingressos
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - rabbitmq
    ports:
      - '3000:8081'


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db  # O nome do serviço do MySQL (db)
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ''  # Senha do root, se necessário
    ports:
      - '8082:80'
    depends_on:
      - db


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta padrão do RabbitMQ
      - "15672:15672"     # Interface de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always


volumes:
  mysql_data: